import { Skill } from '../Data/Skill';

export const SkillsData: Skill[] = [
    { key: '.NET', description: 'A versatile and widely-used framework developed by Microsoft, .NET is utilized for building, deploying, and running applications on Windows, Linux, and macOS platforms. It supports multiple programming languages, including C#.' },
    { key: 'C#', description: 'A powerful, object-oriented programming language developed by Microsoft, C# is commonly used for creating Windows applications, web services, and games. It is known for its robustness, ease of use, and strong support for modern programming concepts.' },
    { key: 'C++', description: 'A high-performance programming language, C++ is ideal for system/software development and real-time applications. It combines low-level and high-level features, offering efficiency and control over hardware resources. Widely used in performance-critical environments.' },
    { key: 'Working under pressure', description: 'As a highly resilient and composed individual, I have developed a reputation for maintaining a calm and level-headed approach, even in high-pressure situations. Throughout my career, I have been faced with numerous challenges and obstacles, and I have consistently demonstrated my ability to remain focused and composed, even when others may be feeling overwhelmed or stressed.' },
    { key: 'PowerShell', description: 'A task automation and configuration management framework developed by Microsoft. PowerShell is a powerful scripting language that allows to automate repetitive tasks and manage various systems efficiently.' },
    { key: 'Angular', description: 'Angular is a widely used open-source framework for building web applications. Developed and maintained by Google, Angular provides developers with a set of tools and components that allow them to create dynamic, interactive, and responsive web applications.'},
    { key: 'REST API', description: 'RESTful APIs provide a standardized way for applications to access and manipulate resources, such as files, on a server. They use HTTP methods, such as GET, POST, PUT, and DELETE, to perform operations on resources, and they return responses in a standard format, such as JSON or XML.'},
    { key: 'Git', description: 'A widely-used, distributed version control system designed to manage and track changes in source code. Git enables collaboration among team members, allows for efficient code branching and merging, and is an essential tool for software development.' },
    { key: 'Windows Server', description: 'A range of server operating systems developed by Microsoft that provide features for managing networks, applications, and data storage. Windows Server is known for its stability, security, and ease of administration.' },
    { key: 'Jira', description: 'A popular project management and issue-tracking software developed by Atlassian. Jira enables teams to plan, track, and release software effectively, providing a centralized platform for collaboration, reporting, and workflow customization.' },
    { key: 'Confluence', description: 'A collaboration and knowledge management tool developed by Atlassian. Confluence enables teams to create, share, and organize documentation, facilitating effective communication and collaboration within organizations.' },
    { key: 'Jenkins', description: 'An open-source automation server that helps automate parts of the software development process, including building, testing, and deploying applications. Jenkins supports continuous integration and continuous delivery, allowing for faster and more reliable software releases.' },
    { key: 'Groovy', description: 'A dynamic, object-oriented programming language that runs on the Java platform. Groovy is known for its concise syntax, seamless integration with Java, and support for scripting and domain-specific languages. I use it mainly to create pipeline on Jenkins.' },
    { key: 'Citrix XenDesktop', description: 'A desktop virtualization solution developed by Citrix Systems that allows users to access their applications and desktops remotely. XenDesktop provides centralized management, scalability, and security for virtual desktop infrastructure (VDI).' },
    { key: 'Bitbucket', description: 'A web-based version control repository hosting service by Atlassian, designed for source code and development projects using either Mercurial or Git revision control systems. Bitbucket offers collaboration features, such as pull requests and code reviews, and integrates with other Atlassian tools.' },
    { key: 'Nexus', description: 'With Nexus, I can access mainframe resources and data from remote locations, using a secure and reliable connection. It provides a centralized management console for configuring and managing connections and users, making it easier to maintain a large number of connections.' },
    { key: 'PostgreSQL', description: 'PostgreSQL supports a wide range of advanced features, including transaction management, concurrency control, data integrity, and extensibility, making it suitable for use in both small and large-scale applications. It also supports a variety of programming languages, including: C++, C#, Java, Python, Ruby.' },
    { key: 'English', description: 'As a fluent English speaker, I have gained valuable experience working as a direct point of contact with customers from Ireland for over 9 months. During this time, I communicated with customers on a daily basis, providing them with information, answering their queries, and resolving their issues.' },
];